### ISSUE TITLE
Refactor Access Grants and Access Receipts

### ISSUE THREAD

**Issue by justinwb** [solid/data-interoperability-panel#149]
- [ ] Change Access Grant Registry to Data Consent Registry, and only use Access Grants and Data Grants for recording and communicating access to recipients. Establish additional class for Data Consent which contains internal information about the consent that should not be shared with recipients.
- [ ] [Remove remote data grants](https://github.com/solid/data-interoperability-panel/issues/143) / referenced remote data grants (move into scopes where applicable)
- [ ] Access receipts point back to source grants instead of copying data inline
- [ ] [Remove referenced data grants](https://github.com/solid/data-interoperability-panel/issues/124)
- [ ] Remove referenced access needs
- [ ] [Define data grants as immutable](https://github.com/solid/data-interoperability-panel/issues/142)
- [ ] [Add who owns the data into data grants](https://github.com/solid/data-interoperability-panel/issues/140), moving what’s already in the receipt into each individual grant
-- This will help a lot with the limited control scenarios too
- [ ] [Support specific shapes for data grant scopes](https://github.com/solid/data-interoperability-panel/issues/109)
- [ ] [Ensure allinstances scope takes referenced types into accounts](https://github.com/solid/data-interoperability-panel/issues/118)
- [ ] Split data grants out of access grants
- [ ] Add delegated data grants
- [ ] Determine how to dynamically authorize access to reference lists on inherited instances scope
- [ ] [Define means for access grant subject to verify access receipt](https://github.com/solid/data-interoperability-panel/issues/107)
- [ ] [Ensure that access grants can support limited control scenarios](https://github.com/solid/data-interoperability-panel/issues/100)

**Comment by elf-pavlik** [comment]
We should also re-evaluate naming of scopes. For example *AllRemoteFromAgent* -> *AllFromAgent* which would also address #113 We might also define *All* as everyone's data including case where Requesting Party === Data Owner. Which means we might consider adding convenience of  *AllFromOthers* which would exclude that case. The last one to be honest I'm not sure of scenario where one would want to use. It sounds weird to give consent for everyone else data but not mine 🤔

**Comment by justinwb** [comment]
> We should also re-evaluate naming of scopes.

Agree 👍  - given all of the modifications we're making we need to ensure the scope names are all accurate and sensible

> We might also define _All_ as everyone's data including case where Requesting Party === Data Owner

Really like this idea about providing more rules around the "parts" of the scope names (e.g. defining what qualifies as All)

> Having many to many here would require selection of which particular registrations the inherited access would apply to. I think it might turn into a real mess if we go that way.

+1

> * Every Data Registry MUST have maximum one Data Registration for given Shape Tree
> * Every Storage SHOULD have maximum one Data Registry

+1

**Comment by elf-pavlik** [comment]
I created issue for: Re-evaluate naming and meaning of scopes used in Data Consent and Data Grant #155

**Comment by justinwb** [comment]
Note - all of these tasks / issues are now being tracked individually in the project, so this mega-issue can be closed.
